package dev.yukaribox.vpn.ui.kit

import android.content.res.AssetManager
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.unit.Dp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.IOException
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

/**
 * The country flag on a server row: a flat greyscale rectangle from `assets/flags/`, one
 * WebP per ISO 3166-1 alpha-2 code, generated by `design/tools/make_flag_assets.py`.
 *
 * Baked rather than drawn from the platform's emoji font, which was the previous answer
 * and is the reason this file exists twice over: an emoji flag is a *waving sticker* with
 * a shaded fold, and the reference draws flat rectangles. Baking also makes the row look
 * the same on every device instead of inheriting whichever emoji set the ROM ships, and
 * it moves the greyscale conversion out of the app — the generator does the colour work
 * in linear light and asserts `R == G == B` on every pixel it writes, so nothing at
 * runtime has to be trusted with hue. Re-run that script to change a flag; never edit a
 * WebP by hand.
 *
 * Two things the assets already encode, so no call site decides them: the flag is
 * stretched to the plate's aspect where its own is close enough (as the reference does,
 * whose US and UK flags fill a 37 x 25 slot) and fitted with **transparent** padding
 * where it is not (Switzerland, Nepal), the transparency letting the plate's own fill
 * show through in either theme.
 *
 * A missing file is the fallback, not an error: [FlagPlate] draws the two-letter code
 * whenever this returns `null`, which covers a code the set does not have and — because
 * the code is checked for shape before it reaches [AssetManager] — anything that is not
 * two ASCII letters.
 */
internal object FlagArt {

    /**
     * Cache bound, in **bytes** of decoded bitmap.
     *
     * Counting entries was counting the wrong thing, and the arithmetic that justified 256 of
     * them was wrong as well: the plate is 37 x 25 **dp**, and [load] scales to a pixel
     * height, so at density 3 one entry is 111 x 75 ARGB_8888 = 33 KB and not "under 4 KB".
     * A full set was therefore ~8.2 MB retained for the life of the process, ~11 MB at
     * density 3.5 -- the ceiling grew with the display it was supposed to be independent of.
     * A byte budget costs the same everywhere; a group larger than it evicts its coldest
     * entries instead of charging whatever the device happens to charge.
     *
     * 2 MB still holds roughly sixty countries at density 3, which covers an ordinary
     * subscription outright, so the mid-scroll re-decoding the old bound was raised to avoid
     * stays avoided for every list that is not a tour of the whole world.
     */
    private const val CAPACITY_BYTES = 2L * 1024 * 1024

    private const val DIR = "flags"

    private const val CODE_LENGTH = 2

    private const val BYTES_PER_PIXEL = 4

    /**
     * A completed lookup. [bitmap] is null when the set has no file for that code.
     *
     * [tick] is the entry's recency stamp, bumped by [hit] on every read. It is what lets the
     * read path stay lock-free and still leave [trim] a true LRU: recording an access used to
     * mean mutating an access-ordered map, i.e. taking the cache monitor from composition.
     */
    class Hit(val bitmap: ImageBitmap?) {
        @Volatile
        internal var tick: Long = 0
    }

    /**
     * Keyed by code and by the pixel height asked for, so a density change re-scales.
     *
     * A [ConcurrentHashMap] so that [hit] -- which runs during the composition of a row that
     * has just scrolled into view, i.e. on the main thread -- never waits on a monitor. The
     * access-ordered `LinkedHashMap` this replaces was written by the decoder threads while
     * they held it through an eviction sweep, so a fling over a list touring more countries
     * than the byte budget holds could block the UI thread inside [trim]. Recency now rides
     * on [Hit.tick] instead.
     *
     * The map holds [Hit], not a nullable bitmap, because a `ConcurrentHashMap` takes no null
     * values and "the set has no file for this code" is a result worth caching.
     */
    private val cache = ConcurrentHashMap<String, Hit>(INITIAL_CAPACITY)

    private const val INITIAL_CAPACITY = 64

    /** Monotonic read counter behind [Hit.tick]. */
    private val clock = AtomicLong(0)

    /** Writer-side lock: taken by [flag] around insertion and eviction, never by [hit]. */
    private val writeLock = Any()

    /** Decoded bytes currently held in [cache]. Guarded by [writeLock]. */
    private var cachedBytes = 0L

    private fun key(code: String, heightPx: Int) = "${code.lowercase()}@$heightPx"

    /**
     * What is already decoded for [code] at [heightPx], or `null` when this pair has not
     * been looked up yet. Never touches the disk, so it is safe to call from composition.
     */
    fun hit(code: String, heightPx: Int): Hit? {
        if (heightPx <= 0 || !isCode(code)) return Hit(null)
        return cache[key(code, heightPx)]?.also { it.tick = clock.incrementAndGet() }
    }

    /**
     * The flag for [code] at [heightPx], or `null` when the set has none. Opens and
     * decodes an asset on a miss, so call it off the main thread — [rememberFlag] does.
     */
    fun flag(assets: AssetManager, code: String, heightPx: Int): ImageBitmap? {
        if (heightPx <= 0 || !isCode(code)) return null
        val name = code.lowercase()
        val key = key(code, heightPx)
        cache[key]?.let { return it.bitmap }
        // Decoded outside the lock: two rows arriving on the same new country would
        // otherwise queue one behind the other's file read, and the loser only writes a
        // duplicate of what the winner already cached.
        val loaded = load(assets, name, heightPx)
        synchronized(writeLock) {
            val entry = Hit(loaded).also { it.tick = clock.incrementAndGet() }
            if (cache.putIfAbsent(key, entry) == null) {
                cachedBytes += loaded.decodedBytes()
                trim()
            }
        }
        return cache[key]?.bitmap
    }

    /**
     * Drop everything. Called from `YukariApp.onTrimMemory`: this is the app's only large
     * retained allocation and it is pure cache -- every entry can be decoded again from
     * assets, at the cost of one plate showing its two-letter fallback while it does.
     */
    fun clear() = synchronized(writeLock) {
        cache.clear()
        cachedBytes = 0L
    }

    /**
     * Evict the coldest entries until the byte budget is met. The caller holds [writeLock].
     *
     * A scan for the minimum [Hit.tick] per eviction rather than an iteration over an
     * access-ordered map: the budget holds on the order of sixty plates, so finding the least
     * recently read one is a few dozen comparisons, and it buys a read path that takes no
     * lock at all.
     */
    private fun trim() {
        while (cachedBytes > CAPACITY_BYTES) {
            val coldest = cache.entries.minByOrNull { it.value.tick } ?: return
            cache.remove(coldest.key)
            cachedBytes -= coldest.value.bitmap.decodedBytes()
        }
    }

    /** ARGB_8888, which is what [BitmapFactory] and [Bitmap.createScaledBitmap] produce here. */
    private fun ImageBitmap?.decodedBytes(): Long =
        if (this == null) 0L else width.toLong() * height * BYTES_PER_PIXEL

    private fun load(assets: AssetManager, name: String, heightPx: Int): ImageBitmap? {
        val decoded = try {
            assets.open("$DIR/$name.webp").use { BitmapFactory.decodeStream(it) }
        } catch (_: IOException) {
            null
        } ?: return null
        if (decoded.height == heightPx) return decoded.asImageBitmap()
        val width = (decoded.width.toFloat() * heightPx / decoded.height).toInt().coerceAtLeast(1)
        val scaled = Bitmap.createScaledBitmap(decoded, width, heightPx, true)
        if (scaled !== decoded) decoded.recycle()
        return scaled.asImageBitmap()
    }

    /** Two ASCII letters, checked before any of it reaches a file name. */
    private fun isCode(code: String) =
        code.length == CODE_LENGTH && code.all { it in 'A'..'Z' || it in 'a'..'z' }
}

/**
 * [FlagArt.flag] at composition, in dp, remembered per code and density.
 *
 * Never decodes inside composition. `assets.open` + `BitmapFactory.decodeStream` +
 * `Bitmap.createScaledBitmap` is file IO, and doing it in the composition of a row that
 * had just scrolled into view dropped a frame for every country the cache had not seen —
 * on a first pass through a large multi-country group, most of them.
 *
 * So a cache hit is returned during composition (the row draws its flag on its first
 * frame) and only a miss suspends: the row shows [FlagPlate]'s two-letter fallback for as
 * long as the decode takes, then swaps. That costs one brief letter plate per country per
 * process, against a dropped frame every time one scrolled into view.
 */
@Composable
internal fun rememberFlag(code: String, height: Dp): ImageBitmap? {
    val assets = LocalContext.current.assets
    val heightPx = with(LocalDensity.current) { height.roundToPx() }
    val hit = remember(code, heightPx) { FlagArt.hit(code, heightPx) }
    if (hit != null) return hit.bitmap
    // A keyed holder rather than `produceState`, whose backing state is remembered
    // *unkeyed*: on a key change it keeps the previous value until the new producer
    // assigns, so a plate whose country changed drew the old country's flag under the new
    // one's contentDescription for a frame or two. `remember(code, heightPx)` resets.
    val loaded = remember(code, heightPx) { mutableStateOf<ImageBitmap?>(null) }
    LaunchedEffect(code, heightPx) {
        loaded.value = withContext(Dispatchers.IO) { FlagArt.flag(assets, code, heightPx) }
    }
    return loaded.value
}
